name: Custom Logic
#show multiline comments
#line 1
#line 2

on: 
  #show different triggers 
  workflow_dispatch:    

jobs:
          
  custom_logic: 
    runs-on: [self-hosted, DevDayXIII]
    
    steps:
      - name: Run Powershell script
        run: "c:\\utils\\ps_demo.ps1"

      - name: Run custom console application
        run: ConsoleApp1
        
      - name: Call API
        run: | 
          Invoke-Webrequest -Headers @{ `
            'Accept' = 'application/json'; `
            'ontent-Type' = 'application/json'; `
            'x-rapidapi-key' = 'dc1dfc1c3fmsh4b6f2a2722a84c2p156bf9jsn2fa8d7b6b4d1' `
          } `
          https://google-translate1.p.rapidapi.com/language/translate/v2/languages  `
          -UseBasicParsing 
      
