name: Custom Logic

on:
  workflow_dispatch:    
    inputs:
      logLevel:
        description: 'Event Serial'     
        required: true
        default: 'XIII'
        
jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo "EMEA DevDay: ${{ github.event.inputs.logLevel }}"
          
      - name: Run custom console application
        run: ConsoleApp1
        
      - name: Run Powershell script
        run: "c:\\utils\\ps_demo.ps1"
        
      - name: Call API
        run: | 
          Invoke-Webrequest -Headers @{ `
            'Accept' = 'application/json'; `
            'ontent-Type' = 'application/json'; `
            'x-rapidapi-key' = 'dc1dfc1c3fmsh4b6f2a2722a84c2p156bf9jsn2fa8d7b6b4d1' `
          } `
          https://google-translate1.p.rapidapi.com/language/translate/v2/languages  `
          -UseBasicParsing 
      
