# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: dotnet restore ${{ secrets.SOURCE }} #"C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln"
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: stop app
      run: powershell  ${{ secrets.SCRIPTS }} + "stopserver.ps1"
    - name: publish
      run: dotnet publish ${{ secrets.SOURCE }} -o ${{ secrets.PUBLISH_PATH }} #"C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln" -o "c:\publish"
    - name: start app
      run: powershell "C:\Utils\startserver.ps1"
