name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: dotnet restore ${{ secrets.SOURCE }} #"C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln"
    - name: Build
      run: dotnet build --no-restore
    - name: stop app
      run: powershell ${{ secrets.STOP_SCRIPT }} #"C:\Utils\stopserver.ps1"
    - name: publish
      run: dotnet publish ${{ secrets.SOURCE }} -o ${{ secrets.PUBLISH_PATH }} #"C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln" -o "c:\publish"
    - name: start app
      run: powershell ${{ secrets.START_SCRIPT }} #"C:\Utils\startserver.ps1"
