name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: dotnet restore "C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln"
    - name: Build
      run: dotnet build --no-restore
    - name: stop app
      run: iisreset /stop
    - name: publish
      run: dotnet publish "C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\WebApplication3.sln" -o "c:\publish"
    - name: start app
      run: iisreset /start
