name: Deploy with secrets

on:
  workflow_dispatch:

jobs:
  deploy_with_secrets:
    runs-on: [self-hosted, DevDayXIII]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: dotnet restore ${{ secrets.SOURCE }} #raise error
    - name: Build
      run: dotnet build --no-restore
    - name: stop app
      run: iisreset /stop 
    - name: publish
      run: dotnet publish ${{ secrets.SOURCE }} -o ${{ secrets.PUBLISH_PATH }} 
    - name: start app
      run: iisreset /start
