name: Deploy JDF

on: 
  workflow_dispatch:

jobs:
  job_1:
    name: Deploy Starter Kit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploying Starter Kit
  job_2:
    name: Deploy Agility Kit
    needs: job_1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploying Agility Kit

  job_3:
    if: 1=0
    name: Deploy Analytics Kit
    needs: job_1
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploying Analytics Kit
