name: CI Demo

on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: [Linux, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
